'use strict';

define([],function(){

  return {
    system:{
      abstract:true,
      title:'布局',
      route:'system',
      /*如果abstract != true url 前面一定要加 '/' 不然路由会不到正确位置 */
      url:'',
      /*这个地址是相对 app 而不是 scripts 。只有需要引入的 .js 文件才是相对 scripts 的*/
      templateUrl:'views/app.html',
      controller:'appController'
    },
    login:{
      title:'登录',
      route:'system.login',
      url:'/login',
      templateUrl:'views/system/login.html',
      controller:'loginController'
    },
    clinic:{
      abstract:true,
      title:'诊所后台',
      route:'system.clinic',
      url:'/clinic',
      templateUrl:'views/system/mainLayout.html',
      controller:'mainLayoutController',
      menus:{
        searchDoctor:{
          title:'医生搜索',
          route:'system.clinic.searchDoctor',
          url:'/searchDoctor',
          templateUrl:'views/searchDoctor/searchDoctor.html',
          controller:'searchDoctorController'
        },
        identification:{
          title:'认证申请',
          child:{
            verifying:{
              title:'待审核',
              route:'system.clinic.verifying',
              url:'/verifying',
              templateUrl:'views/verify/verifying.html',
              controller:'verifyingController'
            },
            verified:{
              title:'已审核',
              route:'system.clinic.verified',
              url:'/verified',
              templateUrl:'views/verify/verified.html',
              controller:'verifiedController'
            }
          }
        },
        privateDoctor:{
          title:'私家医生',
          child:{
            waitVerify:{
              title:'待审核',
              route:'system.clinic.waitVerify',
              url:'/waitVerify',
              templateUrl:'views/privateDoctor/waitVerify.html',
              controller:'waitVerifyController'
            },
            doctorTeam:{
              title:'医生团队',
              route:'system.clinic.doctorTeam',
              url:'/doctorTeam',
              templateUrl:'views/privateDoctor/doctorTeam.html',
              controller:'doctorTeamController'
            },
            addArchive:{
              title:'新增档案',
              route:'system.clinic.addArchive',
              url:'/addArchive',
              templateUrl:'views/privateDoctor/addArchive.html',
              controller:'addArchiveController'
            },
            queryArchive:{
              title:'档案查询',
              route:'system.clinic.queryArchive',
              url:'/queryArchive',
              templateUrl:'views/privateDoctor/queryArchive.html',
              controller:'queryArchiveController'
            }
          }
        },
        clinic:{
          title:'诊所',
          route:'system.clinic.clinic',
          url:'/clinic',
          templateUrl:'views/clinic/clinic.html',
          controller:'clinicController'
        },
        officeWebsite:{
          title:'官网后台',
          child:{
            slider:{
              title:'首页幻灯片',
              route:'system.clinic.slider',
              url:'/slider',
              templateUrl:'views/officialWebsite/slider.html',
              controller:'sliderController'
            },
            article:{
              title:'新闻资讯',
              route:'system.clinic.article',
              url:'/article',
              templateUrl:'views/officialWebsite/article.html',
              controller:'articleController'
            },
            aboutAs:{
              title:'关于我们',
              route:'system.clinic.aboutAs',
              url:'/aboutAs',
              templateUrl:'views/officialWebsite/aboutAs.html',
              controller:'aboutAsController'
            }
          }
        },
        authorityManagement:{
          title:'权限管理',
          child:{
            roleManage:{
              title:'角色管理',
              route:'system.clinic.roleManage',
              url:'/roleManage',
              templateUrl:'views/authorityManagement/roleManage.html',
              controller:'roleManageController'
            },
            userManage:{
              title:'用户管理',
              route:'system.clinic.userManage',
              url:'/userManage',
              templateUrl:'views/empty.html',
              controller:''
            }
          }
        }
      }
    }
  };
});
