/**
 * Created by ASUS on 2015/12/22.
 */
'use strict';

define([],function(){
   return {
     submenus:[
       {
         key:'searchDoctor',
         title:'医生搜索',
         role_id:1,
         sort:1
       },
       {
         key:'identification',
         title:'认证申请',
         role_id:1,
         sort:2,
         submenus:[
           {
             key:'verifying',
             title:'待审核',
             role_id:1,
             sort:2.1
           },
           {
             key:'verified',
             title:'已审核',
             role_id:1,
             sort:2.2
           }
         ]
       },
       {
         key:'privateDoctor',
         title:'私家医生',
         role_id:1,
         sort:3,
         submenus:[
           {
             key:'waitVerify',
             title:'待审核',
             role_id:1,
             sort:3.1
           },
           {
             key:'doctorTeam',
             title:'医生团队',
             role_id:1,
             sort:3.2
           },
           {
             key:'addArchive',
             title:'档案新增',
             role_id:1,
             sort:3.3
           },
           {
             key:'queryArchive',
             title:'档案查询',
             role_id:1,
             sort:3.4
           }
         ]
       },
       {
         key:'clinic',
         title:'诊所',
         role_id:1,
         sort:4
       },
       {
         key:'officeWebsite',
         title:'官网后台',
         role_id:1,
         sort:5,
         submenus:[
           {
           key:'slider',
           title:'首页幻灯片',
           role_id:1,
           sort:5.1
         },
         {
           key:'article',
           title:'新闻资讯',
           role_id:1,
           sort:5.2
         },
         {
           key:'aboutAs',
           title:'关于我们',
           role_id:1,
           sort:5.3
         }
         ]
       },
       {
         key:'authorityManagement',
         title:'权限管理',
         sort:5,
         submenus:[
           {
             key:'roleManage',
             title:'角色管理',
             sort:5.1
           },
           {
             key:'userManage',
             title:'用户管理',
             sort:5.2
           }
         ]
       }
     ]
   }
});
